version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db/invoices
      - DATABASE_USER=root
      - DATABASE_PASSWORD=pass
    depends_on:
      - db
    command: sh -c "./gradlew run --parallel"
    volumes:
      - ./:/app
      - ./run/gradle-cache:/app/.gradle

  db:
    image: mysql:8.0
    ports:
      - "5306:3306" # ホストポート 5306 をコンテナポート 3306 にマッピング
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=invoices

  flyway:
    image: flyway/flyway:latest
    command: ["migrate"]
    environment:
      - FLYWAY_URL=jdbc:mysql://db/invoices?allowPublicKeyRetrieval=true # コンテナ内のポート
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=pass
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db
    restart: on-failure
